# fly.toml app configuration file generated for mentor-matcher-twilight-lake-6255 on 2024-08-30T15:16:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mentor-matcher'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'
  TRANSPORT_SCHEME = 'https'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
